### ISSUE TITLE
Please Clarify Readme.md - What does this XLR plugin do?

### ISSUE THREAD

**Issue by andrewnaut** [xebialabs-community/xlr-flowdock-plugin#2]
It's not clear from the readme exactly what does this plugin do?  I understand it allows me to create a Flowdock configuration in settings, great but then what?  Which XLR Tasks can use that configuration? Which messages get sent to flowdock?
Thank you,
Andy

**Comment by jdewinne** [comment]
Thanks. I've update the [usage](https://github.com/xebialabs-community/xlr-flowdock-plugin#usage) information.
